dqProfileApp:
  mssql:
    url: ""
    username: ""
    password: ""
spring:
  application:
    name: "DQ Profiler App"
  main:
    web-application-type: none
  datasource:
    jdbcUrl: "${dqProfileApp.mssql.url}"
    username: "${dqProfileApp.mssql.username}"
    password: "${dqProfileApp.mssql.password}"