dqProfileApp:
  mssql:
    url: ""
    username: ""
    password: ""
  qns-svc:
    baseUrl: ""
    code: ""
  jsoncreator-svc:
    baseUrl: ""
    code: ""
  atlaswrapper-svc:
    baseUrl: ""
    code: ""
  updateColumnScores:
    queryAll: true # dictates if all the entries of the view will be queried or just the ones in the time range
  upsertDQRules:
    queryAll: true # dictates if all the entries of the table will be queried or just the ones in the time range
spring:
  jmx:
    default-domain: com.ms.cse
    unique-names: true
  application:
    name: "DQ Profiler App"
  main:
    web-application-type: none
  datasource:
    jdbcUrl: "${dqProfileApp.mssql.url}"
    url: "${dqProfileApp.mssql.url}"
    username: "${dqProfileApp.mssql.username}"
    password: "${dqProfileApp.mssql.password}"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver